#!/bin/bash 

# Check if `react-scripts` is installed locally 
if ! npm list react-scripts --depth=0 | grep -iq 'react-scripts'; then 
  npm install react-scripts 
fi 

# Check if serve is installed globally
if ! npm list -g serve --depth=0 | grep -iq 'serve'; then 
  npm install -g serve 
fi

# Start the development server
npm start 